### ISSUE TITLE
How can I override hash256 of wine-wechat

### ISSUE THREAD

**Issue by yswtrue** [xddxdd/nur-packages#10]
Wechat has release new version now, and can I make a overlay of wine-wechat to make it work again.

**Comment by yswtrue** [comment]
Can you update .exe file in git repository to fix version?

**Comment by xddxdd** [comment]
WeChat exe file has been updated. In addition, from now on you can do `(wine-wechat.override { version = "1.2.3"; sha256 = "xxx";})` if WeChat updates again.
