### ISSUE TITLE
dingtalk launch failed!

### ISSUE THREAD

**Issue by jinzhongjia** [xddxdd/nur-packages#12]
dingtalk fails to start from terminal with no output，I don't know what the reason is

**Comment by xddxdd** [comment]
Right now I'm unable to fix the issue.

With git bisecting I know that some change happened between https://github.com/NixOS/nixpkgs/commit/a2df1eb5b9e78f1181dfdb97e2ed5914e70b2a67 and https://github.com/NixOS/nixpkgs/commit/b2e39759f30441f9912cbbcfaa095ebc392ca5c3 that broke DingTalk, but I don't know what that change is, and I can't continue bisecting as each run will require rebuilding all dependencies (the packages aren't binary cached).

**Comment by xddxdd** [comment]
Dingtalk has been fixed, problem is with the recent update of harfbuzz package.

**Comment by jinzhongjia** [comment]
thanks, and I started using nixos recently with your article
