### ISSUE TITLE
linux-xanmod-lantian: refactor config parsing

### ISSUE THREAD

**Issue by milahu** [xddxdd/nur-packages#2]
hey : )

i forked your [pkgs/linux-xanmod-lantian](https://github.com/xddxdd/nur-packages/tree/master/pkgs/linux-xanmod-lantian) and came up with [pkgs/linux-firecracker](https://github.com/milahu/nur-packages/blob/master/pkgs/linux-firecracker/default.nix)

i use only `config` and generate `config.nix` on-the-fly

**Comment by milahu** [comment]
its even easier than that ... the `config` parameter is optional,
default value is parsed from `configfile` per [kernel/manual-config.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/manual-config.nix#L36)

**Comment by xddxdd** [comment]
Hi milahu,

Thanks for your suggestion! Actually, if I don't specify config.nix, I will get this error when building on GitHub Actions:

```
error: cannot import '/nix/store/0l1r7nqcxzamkcff7p5qjsx9cnjsa1s1-config.nix', since path '/nix/store/bmz42nhm7hl44sixfqrkpx3f20zjv28i-config.nix.drv' is not valid
```

Copying the generation code from <https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/manual-config.nix#L36> and generating `config.nix` fixed the problem, so I just kept using this workaround.

Have you tried building on GitHub Actions and have you seen this problem before?

**Comment by milahu** [comment]
oh i see ... no experience with gh-actions here

i can only say the error comes from [nix/src/libexpr/primops.cc](https://github.com/NixOS/nix/blob/master/src/libexpr/primops.cc#L119)

maybe add a `.out` or `.outPath` after the derivation?
