### ISSUE TITLE
wine-wechat: hash mismatch 

### ISSUE THREAD

**Issue by lz37** [xddxdd/nur-packages#23]
error:
> error: hash mismatch in fixed-output derivation '/nix/store/903ps49dlzlf3cbb09mh0w56a8sydxnr-WeChatSetup.exe?v=3.9.2.drv':
         specified: sha256-9zAHsy3zzp5x+RSL70vgf/EDkPQyxpORdeF79F3AhsY=
            got:    sha256-tflNuSQQ/Z4L1FcLxzX21Q10AuntmtorijGCIgax/zA=
> error: 1 dependencies of derivation '/nix/store/q5gy7818qw20k5c21cnx8gqkwgkx2km5-wechat-3.9.2.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/y6jlkflscrkh0lkl87ffzfnwigz9r693-wine-wechat.drv' failed to build
> error (ignored): error: cannot unlink '/tmp/nix-build-wine-8.0.drv-1/wine-8.0': Directory not empty
> error: 1 dependencies of derivation '/nix/store/vmrnxf3dpm1j4fvbrb19y41ng1afjqih-wine-wechat-3.9.2.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/nk900lin1a0fniksp1v7iydn5c4hjzkk-system-path.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/aivfhyw57f9rnkjga9pw3d9rshql4iz8-nixos-system-zawanix-23.05.20230810.18784aa.drv' failed to build

**Comment by xddxdd** [comment]
This should be fixed now, can you try again?

**Comment by lz37** [comment]
thank you! successfully downloaded but there is error when running

error:

> 002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
> 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> Application could not be started, or no application associated with the specified file.
> ShellExecuteEx failed: Bad EXE format for Z:\nix\store\y3bvkaa21r5pj9p8pyj59y0qpnw2230a-wechat-3.9.6\WeChat.exe.

**Comment by xddxdd** [comment]
Please try again. Looks like the download link provides 64 bit WeChat by default. I've updated the package to use 64 bit wine.

**Comment by lz37** [comment]
thank you very much! it can work on my machine now, thx for your excellent work!

**Comment by xddxdd** [comment]
Glad to hear that!
