### ISSUE TITLE
关于下载微信的问题

### ISSUE THREAD

**Issue by SuperKenVery** [xddxdd/nur-packages#29]
您好，我找到了一个repo专门收集各个版本的微信：
https://github.com/tom-snow/wechat-windows-versions/releases

您看可否考虑一下从这里下载？这样就不容易build不起来了。

顺便，您仓库里的wine-wechat是3.9.7的，但NUR里的好像还是3.9.2,不知道是不是我自己配置写错了
:rofl:

**Comment by xddxdd** [comment]
感谢建议，已经把微信下载链接切换到这个仓库。

NUR 没更新的原因是我的配置有点复杂导致 eval 耗时超出了 NUR 的限制，现在已经处理，稍后 NUR 搜索页应该就会更新。

**Comment by SuperKenVery** [comment]
感谢！
