### ISSUE TITLE
svp: separate MPV instances

### ISSUE THREAD

**Issue by Diamondy4** [xddxdd/nur-packages#31]
Duplicating comment here https://github.com/NixOS/nixpkgs/pull/254332#issuecomment-1811638868

Hello @xddxdd,

I'm encountering an issue when trying to connect independently opened MPV to SVP. When I launch MPV with `--input-ipc-server=/tmp/mpvsocket` (or same global conf), SVP fails to connect with error message `VideoPlayer: unable to find mpv's PID`.

It seems that the buildFHSEnv (bubblewrap) is creating an environment where lsof can't detect process IDs outside of it, even with false unsharePid/unshareIpc.

This issue particularly affects scenarios where applications launch MPV with some opaque args, yt-dlp like. Since SVP’s MPV integration is primarily GUI-based, these instances fail to connect to SVP.

Could you provide any guidance for enabling SVP to connect with MPV instances opened this way?

**Comment by xrun1** [comment]
I've hit this problem too and couldn't get it to work, as much as I tried to mess with bubblewrap's arguments. To install https://github.com/NixOS/nixpkgs/pull/254332 with Home Manager, I've resorted to this hack:
```nix
home.packages = [(svp-bin.override {
    lsof = pkgs.writeShellApplication {
        name = "lsof";
        runtimeInputs = with pkgs; [socat jq];
        text = ''
            for arg in "$@"; do
                if [ -S "$arg" ]; then
                    printf %s p
                    echo '{"command": ["get_property", "pid"]}' |
                        socat - "UNIX-CONNECT:$arg" |
                        jq -Mr .data
                    printf '\n'
                fi
            done
        '';
    };
})];
```
SVP runs `lsof MPV_SOCKET_PATH` and expects a `pMPV_PID` output, so I replace lsof inside the package's environment with a script that sends a command through the socket to output the same thing.

**Comment by Diamondy4** [comment]
> I've hit this problem too and couldn't get it to work, as much as I tried to mess with bubblewrap's arguments. To install [NixOS/nixpkgs#254332](https://github.com/NixOS/nixpkgs/pull/254332) with Home Manager, I've resorted to this hack:
> 
> ```nix
> home.packages = [(svp-bin.override {
>     lsof = pkgs.writeShellApplication {
>         name = "lsof";
>         runtimeInputs = with pkgs; [socat jq];
>         text = ''
>             for arg in "$@"; do
>                 if [ -S "$arg" ]; then
>                     printf %s p
>                     echo '{"command": ["get_property", "pid"]}' |
>                         socat - "UNIX-CONNECT:$arg" |
>                         jq -Mr .data
>                     printf '\n'
>                 fi
>             done
>         '';
>     };
> })];
> ```
> 
> SVP runs `lsof MPV_SOCKET_PATH` and expects a `pMPV_PID` output, so I replace lsof inside the package's environment with a script that sends a command through the socket to output the same thing.

Thanks, it detects MPV instance now, but fails with `libOpenCL.so.1` not found error. I do have `/run/opengl-driver/lib` in `LD_LIBRARY_PATH`, and both standalone and in-SVP MPV's derivations are same. Peculiar.

```
[vapoursynth] Python exception: SVSmoothFps: error loading OpenCL: libOpenCL.so.1: cannot open shared object file: No such file or directory
[vapoursynth] 
[vapoursynth] Traceback (most recent call last):
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
[vapoursynth]   File "/home/diamondy4/.local/share/SVP4/scripts/e3a8e084.py", line 56, in <module>
[vapoursynth]     smooth =  interpolate(clip)
[vapoursynth]               ^^^^^^^^^^^^^^^^^
[vapoursynth]   File "/home/diamondy4/.local/share/SVP4/scripts/e3a8e084.py", line 35, in interpolate
[vapoursynth]     smooth  = core.svp2.SmoothFps_NVOF(input_m,smoothfps_params,nvof_src=input_m8,src=input_um,fps=src_fps)
[vapoursynth]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 2860, in vapoursynth.Function.__call__
[vapoursynth] vapoursynth.Error: SVSmoothFps: error loading OpenCL: libOpenCL.so.1: cannot open shared object file: No such file or directory
[vapoursynth] 
[vapoursynth] could not init VS
Disabling filter vapoursynth.00 because it has failed.
```

**Comment by xddxdd** [comment]
I didn't find any workaround for this issue. For my own use case, I just always start MPV from SVP.

**Comment by xddxdd** [comment]
@Diamondy4 @xrun1 

Great news: I have found a workaround to support externally launched MPV players. Please try the latest version from this repo.

Note:
- I recommend you to use my provided MPV, in `packages.x86_64-linux.svp.mpv`.
- If you want to use your own MPV, it must:
  - Have VapourSynth support enabled
  - Have `/run/opengl-driver/lib` and `libOpenCL.so.1` added in its `LD_LIBRARY_PATH`
  - Have `--input-ipc-server=/tmp/mpvsocket` either through commandline arguments or config file
- SVP can only properly activate its plugin if these requirements are met.

Also note that this will not work if you have multiple MPV running simultaneously, even if some of them are not intended for SVP. With that said, I don't expect a lot of people to do that.

**Comment by xrun1** [comment]
Thanks for looking at this. Just looking at the code, I see you made your version of the `lsof`, but the caveat is a deal-breaker as I need multiple mpv instances open in all sorts of situations. Why not just reuse the one I wrote? It will handle all situations flawlessly.

Furthermore, SVP [explicitly supports](https://www.svp-team.com/wiki/SVP:mpv#Basic_settings) the [mpvSockets script](https://github.com/wis/mpvSockets). Since it's not packaged, I use it like this in my home manager flake setup:
```nix
inputs.mpvSockets.url = "github:wis/mpvSockets";
inputs.mpvSockets.flake = false;
...
programs.mpv.config.script = ["${inputs.mpvSockets}/mpvSockets.lua"];
```
Then no need for the `--input-ipc-server` option.
Coming from Arch, I'd love to have an SVP package that just works in Nix too, even for the less obvious use cases.

**Comment by xddxdd** [comment]
@xrun1 Thank you, your script is indeed better than mine. I previously mistakenly thought that your script is calling some other daemon outside the namespace which forwards the `lsof` command result.

I have updated the SVP package to use your script, and no longer add the `--input-ipc-server` by default.

**Comment by xddxdd** [comment]
Since the solution seems working, I will close this issue now. If you see any issues using the latest fix, feel free to reopen.
