### ISSUE TITLE
qemu-user-static fails with conflicts over proc-sys-fs-binfmt_mount.automount

### ISSUE THREAD

**Issue by nikp123** [xddxdd/nur-packages#40]
Hi, thanks for the repo (and especially qemu-user-static thing), it's been a real head-scratcher before I found this.

Anyways, when I try adding a seperate binfmt config (like the example featured in the [AppImages part of the NixOS wiki](https://nixos.wiki/wiki/Appimage)) it fails to build because both the [included nixOS module](https://github.com/NixOS/nixpkgs/blob/8bf65f17d8070a0a490daf5f1c784b87ee73982c/nixos/modules/system/boot/binfmt.nix#L329) and [this one](https://github.com/xddxdd/nur-packages/blob/bd6282fbae36610c7511c3eb5cef77462a1fc8f4/modules/qemu-user-static-binfmt.nix#L233) add a systemd service (I think) which has the same hash therefore causing a conflict.

<details>
<summary>Relevant log:</summary>
<br>

```
nikp123@Wall /e/nixos> sudo nixos-rebuild switch --show-trace
building the system configuration...
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
trace: warning: optionsDocBook is deprecated since 23.11 and will be removed in 24.05
error: builder for '/nix/store/7nnf5ivg03qp28i2s5ha9jkgh7mn478k-system-units.drv' failed with exit code 1;
       last 1 log lines:
       > ln: failed to create symbolic link '/nix/store/iwl29zskyj3z6541nnb2ik9054iia6ya-system-units/proc-sys-fs-binfmt_misc.automount': File exists
       For full logs, run 'nix log /nix/store/7nnf5ivg03qp28i2s5ha9jkgh7mn478k-system-units.drv'.
error: 1 dependencies of derivation '/nix/store/59nvbpimn8gji7b7rpi168vd51xk4gab-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9i0iphwbl6bzg31lqkmmq53hbbpxdj2w-nixos-system-Wall-23.11.20231201.5de0b32.drv' failed to build
```
</details>

PS: This module is included as shown in the README.

**Comment by xddxdd** [comment]
I have updated the module to not add these duplicate services if NixOS's binfmt module is also in use. Can you try again?
