### ISSUE TITLE
can not use qqmusic

### ISSUE THREAD

**Issue by liyjii** [xddxdd/nur-packages#44]
hello,I can't install qqmusic since last update.
`https://dldir1.qq.com/music/clntupate/linux/deb/qqmusic_1.1.5_amd64.deb`
returns 404.

**Comment by xddxdd** [comment]
Fixed in latest commit.

QQ music added an extra underscore in the deb file name. No idea why they did that.

**Comment by liyjii** [comment]
Thank you.
