### ISSUE TITLE
dingtalk meeting failed to start

### ISSUE THREAD

**Issue by AmourAmer** [xddxdd/nur-packages#45]
## Issue
nothing pops up starting dingtalk meet or being called.

## My "solution"

use dingtalk.exe with wineStaging
though characters are tofu and might be solved by passing `LANG=zh_CN.utf8`, I only need meeting on pc so it's acceptable.

BTW, there seems to be an available upstream update

**Comment by xddxdd** [comment]
Please try the latest commit from this repo. I have updated DingTalk to latest version and checked that video meeting is working.

**Comment by AmourAmer** [comment]
thx but, sadly it still doesn't work for me
maybe I'm missing some runtime dependency? This is a brand new nix system
here's a recorded video: https://airportal.cn/34062/ohhJfcB1fD
