### ISSUE TITLE
wechat-uos broken

### ISSUE THREAD

**Issue by Freed-Wu** [xddxdd/nur-packages#49]
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Has MIT-SHM     : true
Has MIT-SHM FD  : true
xcb_shm_attach() failed
failed to create System V shared memory segment (remote X11 connection?), disabling SHM
Using XInput version 2.2
[0717/191334.924382:ERROR:directory_reader_posix.cc(42)] opendir /home/wzy/.xwechat/crashinfo/attachments/eeb61f03-f523-4fc5-9366-1f308f73f57d: No such file or directory (2)
```

both with and without sandbox will break after recent updating.

**Comment by xddxdd** [comment]
I can reproduce this issue, but I cannot pinpoint what change caused this error.

Currently I'm comparing dependencies of known good/bad versions, and trying to replace them one by one, but every try triggers a mass rebuild and takes a long time.

The `wechat-uos` packaged in nixpkgs has the same problem: https://github.com/NixOS/nixpkgs/issues/327860

**Comment by xddxdd** [comment]
I just pushed a change to always use dependencies from nixpkgs 24.05 stable branch, which is known to work. Note that you must use my repo directly for it to work. If you're using my packages like `nur.repos.xddxdd.wechat-uos` then it will still use the latest broken dependencies.

**Comment by Freed-Wu** [comment]
I see, it is repeated by https://github.com/NixOS/nixpkgs/issues/327860

**Comment by xddxdd** [comment]
I have pinpointed the issue and pushed a fix with help of Cryolitia in https://github.com/NixOS/nixpkgs/issues/327860. Can you test the latest version of this repo, and see if WeChat works?

**Comment by Freed-Wu** [comment]
Yes!
