### ISSUE TITLE
wechat-uos broken with nixos-unstable

### ISSUE THREAD

**Issue by L-Trump** [xddxdd/nur-packages#50]
Reopen from #49 

Same problem occured again after the `nixos-unstable` channel update to commit ad416d0

```
> /nix/store/a90bc7k65qdjl9v6c7dn2i92i3ld246h-wechat-uos-1.0.0.241/bin/wechat-uos
Has MIT-SHM     : true
Has MIT-SHM FD  : true
xcb_shm_attach() failed
failed to create System V shared memory segment (remote X11 connection?), disabling SHM
[0906/173328.614697:ERROR:directory_reader_posix.cc(42)] opendir /home/ltrump/.xwechat/crashinfo/attachments/8d59a1da-866c-47f3-9b06-9f6401735b51: No such file or directory (2)
```

**Comment by xddxdd** [comment]
Can you try the latest commit? This is caused by https://github.com/NixOS/nixpkgs/pull/332617

**Comment by L-Trump** [comment]
> Can you try the latest commit? This is caused by [NixOS/nixpkgs#332617](https://github.com/NixOS/nixpkgs/pull/332617)

Its fixed! Thanks!!
