### ISSUE TITLE
wechat-uos broken at 4.0.0.30

### ISSUE THREAD

**Issue by zzzsyyy** [xddxdd/nur-packages#56]
seems to be because the download link has changed

**Comment by xddxdd** [comment]
Thanks for letting me know, I have downgraded `wechat-uos` back to `4.0.0.21` for now. It's difficult to package the universal `wechat` because it does not have version number in the download URL.

**Comment by xddxdd** [comment]
`wechat-uos` is now also available in nixpkgs. If you specifically want sandbox functionality, I have added a new `wechat-uos-sandboxed` package in my NUR that uses the `wechat-uos` in nixpkgs but adds the same sandboxing.

**Comment by zzzsyyy** [comment]
thank you
