### ISSUE TITLE
wine-wechat hash mismatch in fixed-output derivation

### ISSUE THREAD

**Issue by xinyifly** [xddxdd/nur-packages#9]
I think Tencent has updated the installer, caused a hash mismatch.

```
trying https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
...
error: hash mismatch in fixed-output derivation '/nix/store/2xn1r842vsypzki1qnlxpwwk495r8yy7-WeChatSetup.exe.drv':
         specified: sha256-/10wQsQjOEDocCch4l1ycsfdTFXzjQRy2An+Tg69mSo=
            got:    sha256-yRhW0HIbCaEMezcBPKk8q7XmGOp2jmanAUEFKTDAw1E=
```

**Comment by xddxdd** [comment]
Hash has been updated.

Note that Tencent uses the same URL for all versions, so it will inevitably break again in the future, and there's nothing I can do about it.

I recommend to use wechat-uos whenever possible.
